#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8090/eureka/
server:
    port: 6667
spring:
    application:
        name: cst-employee-producer
    config:
        import: configserver:http://localhost:6666
